services:
  api:
    environment:
      - DB_USER=${STAGE_DB_USER}
      - DB_PASSWORD=${STAGE_DB_PASSWORD}
      - DB_NAME=${STAGE_DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8010:8080"

  db:
    environment:
      - POSTGRES_USER=${STAGE_DB_USER}
      - POSTGRES_PASSWORD=${STAGE_DB_PASSWORD}
      - POSTGRES_DB=${STAGE_DB_NAME}
    volumes:
      - stage_db_data:/var/lib/postgresql/data
    mem_limit: 4G

volumes:
  stage_db_data:
